# Generated by Django 5.2.1 on 2025-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales-rep', 'Sales Rep'), ('warehouse-staff', 'Warehouse Staff'), ('neighbor-client', 'Neighbor Client'), ('other-client', 'Other Client'), ('vendor', 'Vendor')], default='other-client', help_text='Designates the user’s role in the system.', max_length=32),
        ),
    ]
