# Generated by Django 5.2.1 on 2025-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales-rep', 'Sales Rep'), ('warehouse-staff', 'Warehouse Staff'), ('neighbor-client', 'Neighbor Client'), ('other-client', 'Other Client'), ('vendor', 'Vendor')], default='other-client', max_length=20),
        ),
    ]
